In [1]:
import tensorflow as tf
import numpy as np

In [2]:
source_texts = ['hello','how are you','goodbye']
target_texts = ['bonjour','comment ca va','au revoir']

In [3]:
source_vocab = set(' '.join(source_texts))
target_vocab = set(' '.join(target_texts))
source_vocab_size = len(source_vocab)
target_vocab_size = len(target_vocab)
print(source_vocab)

{'w', 'g', 'b', 'y', 'u', 'r', ' ', 'l', 'o', 'd', 'a', 'h', 'e'}


In [4]:
source_char_to_int = {char:idx for idx,char in enumerate(source_vocab)}
target_char_to_int = {char:idx for idx,char in enumerate(target_vocab)}
source_int_to_char = {idx:char for char,idx in source_char_to_int.items()}
target_int_to_char = {idx:char for char,idx in target_char_to_int.items()}

In [5]:
source_sequences = [[source_char_to_int[char] for char in text] for text in source_texts]
print(source_sequences)
target_sequences = [[target_char_to_int[char] for char in text] for text in target_texts]

[[11, 12, 7, 7, 8], [11, 8, 0, 6, 10, 5, 12, 6, 3, 8, 4], [1, 8, 8, 9, 2, 3, 12]]


max_sequences_length = max(len(seq) for seq in source_sequences)

In [6]:
max_sequence_length = max(len(seq) for seq in source_sequences)
print(max_sequence_length)
source_sequences = tf.keras.preprocessing.sequence.pad_sequences(source_sequences,maxlen=max_sequence_length,padding='post')
print(source_sequences)
target_sequences = tf.keras.preprocessing.sequence.pad_sequences(target_sequences,maxlen=max_sequence_length,padding='post')

11
[[11 12  7  7  8  0  0  0  0  0  0]
 [11  8  0  6 10  5 12  6  3  8  4]
 [ 1  8  8  9  2  3 12  0  0  0  0]]


In [7]:
input_shape =(max_sequence_length,source_vocab_size)
output_shape =(max_sequence_length,target_vocab_size)

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(source_vocab_size,64,input_length=max_sequence_length),
    tf.keras.layers.SimpleRNN(128,return_sequences=True),
    tf.keras.layers.Dense(target_vocab_size,activation='softmax')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [8]:
target_sequences_one_hot = np.array([tf.keras.utils.to_categorical(seq,num_classes=target_vocab_size) for seq in target_sequences])
print(target_sequences_one_hot)

[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.

In [9]:
model.fit(source_sequences,target_sequences_one_hot,epochs=500)

Epoch 1/500


1/1 [==============================] - 1s 1s/step - loss: 2.6210 - accuracy: 0.0606
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 2.5609 - accuracy: 0.2424
Epoch 3/500
1/1 [==============================] - 0s 15ms/step - loss: 2.4983 - accuracy: 0.4242
Epoch 4/500
1/1 [==============================] - 0s 0s/step - loss: 2.4293 - accuracy: 0.4545
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 2.3508 - accuracy: 0.4545
Epoch 6/500
1/1 [==============================] - 0s 14ms/step - loss: 2.2617 - accuracy: 0.3636
Epoch 7/500
1/1 [==============================] - 0s 0s/step - loss: 2.1670 - accuracy: 0.3333
Epoch 8/500
1/1 [==============================] - 0s 7ms/step - loss: 2.0821 - accuracy: 0.3030
Epoch 9/500
1/1 [==============================] - 0s 9ms/step - loss: 2.0260 - accuracy: 0.3030
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 1.9915 - accuracy: 0.2727
Epoch 11/500
1/1 [==========

In [10]:
input_sequence = "how are you"
input_sequence = [source_char_to_int[char] for char in input_sequence]
input_sequence = tf.keras.preprocessing.sequence.pad_sequences([input_sequence],maxlen=max_sequence_length,padding='post')
output_sequence = model.predict(input_sequence)[0]

1/1 [==============================] - 0s 198ms/step


In [11]:
output_sequence = [target_int_to_char[np.argmax(char)] for char in output_sequence]

In [12]:
print("Input Sequence: how are you ")
print("Translated Sequence:",''.join(output_sequence))

Input Sequence: how are you 
Translated Sequence: mment ca va
